create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  email text unique,
  level text default 'Nao informado',
  status text default 'Ativo',
  is_active boolean generated always as (lower(coalesce(status, '')) in ('active', 'ativo', 'enabled', 'on')) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists students_created_at_idx on public.students (created_at desc);
